### ISSUE TITLE
local: different behavior between fs implementations

### ISSUE THREAD

**Issue by pared** [iterative/dvc-objects#115]
Following script shows different behavior between `LocalFileSystem`, `FsspecLocalFileSystem` and `fsspec.implementations.local.LocalFileSystem`:

```python
from dvc_objects.fs.implementations.local import LocalFileSystem


fs = LocalFileSystem()

try:
    fs.remove("non_existing_file")
except FileNotFoundError:
    print(f"FileNotFoundError for {type(fs)}")

fs = fs.fs # FsspecLocalFileSystem

try:
    fs.rm_file("non_existing_file")
except FileNotFoundError:
    print(f"FileNotFoundError for {type(fs)}")

fs = fs.fs # fsspec.implementations.local.LocalFileSystem

try:
    fs.rm_file("non_existing_file")
except FileNotFoundError:
    print(f"FileNotFoundError for {type(fs)}")
``` 
In `0.1.6` we will get `FileNotFoundError` only for underlying fsspec implementation.
Is this intentional? 

cc @Suor

**Comment by skshetry** [comment]
@pared, do we depend anywhere on this behavior?

**Comment by pared** [comment]
I don't think we depend anywhere, but I think it might result in some ambiguous behavior. For example:
[this discussion](https://github.com/iterative/studio/pull/4082#discussion_r935445972). One of the problems was understanding what is going on. I understand that this might be due to fact of modyfing the fs, but researching such issues in the future would be easier if we keep consistent behavior.

**Comment by efiop** [comment]
@pared Could you post example of the output, please? The script is not self-explanatory, really.

**Comment by skshetry** [comment]
Note that we do depend on the behavior that `rm` does not raise `FileNotFoundError`,
but we don't depend on and don't handle possible `FileNotFoundError`.

So, this requires:
1. Suppressing `FileNotFoundError` properly wherever we call `rm()`, but don't care if the file does not exist.
2. Raising `FileNotFoundError` in the implementation.

This may be obvious, but I wanted to make it clear that we do depend on this behaviour.

**Comment by pared** [comment]
@efiop 
Sorry,
The code will return followign log:
```bash
 FileNotFoundError for <class 'fsspec.implementations.local.LocalFileSystem'>
```

Only fsspec implementation raises the error.

**Comment by efiop** [comment]
Ok, so in that case we need to make our implementations and our code follow what fsspec does (if it is consistent in other filesystems).
