### ISSUE TITLE
DVC FileSystem Plugin

### ISSUE THREAD

**Issue by joncarter1** [iterative/dvc-objects#174]
My organisation uses a custom SMB file system solution for the cache and remote storage. 

Mountpoints vary between users, so our current solution is to use local configs i.e. have each user run:
```
dvc remote add -d storage $HOME/path/to/dvc-store --local
dvc remote add -d storage $HOME/path/to/dvc-cache --local
```
to configure their cache and remote. There is a default remote path stored in the Git repository, but this is only used for Docker deployments.

This works great for most of our use cases. The only scenario that we can't currently see a solution to is when using DVC as a data registry. In particular, `dvc get` uses the default remote stored in the repository, which users don't have access to.

One solution to this problem would be to allow custom protocols discovered using plugins. This idea is inspired by the drive artifact repository plugins used by MLFlow: https://www.mlflow.org/docs/latest/plugins.html#aliyun-alibaba-cloud-oss-plugin.

This would enable us to implement our own custom backend, so that URLs could be specified in the form:
```
['remote "storage"']
    url = mycustomprotocol://path/using/protocol
```
where `mycustomprotocol` is resolved using a custom FileSystem subclass from a plugin that is discovered by DVC at runtime. For example, using the Registry class:
https://github.com/iterative/dvc-objects/blob/a1f8c64f584b78eb1c392b1d129b27ca76811b0a/src/dvc_objects/fs/__init__.py#L90

**Comment by efiop** [comment]
@joncarter1 Usually the way this is handled is you would have default remote (the one used by users) and locally everyone working on this repository would use `.dvc/config.local` to overwrite the default remote to point to `/user/path/to/dvc-store`. This way it should work fine for everyone.

Maybe ^ will be enough for you, but I wonder if you could clarify what custom protocol you were talking about. Like a custom nfs remote? Just curious if there is some confusion here.

**Comment by joncarter1** [comment]
Hi @efiop , thanks for your swift reply.

So in our specific use case our remote store is currently an SMB filesystem which is mounted in user's home directories.
We do use local configs as you've suggested, so that each user's local remote URL config points to `$HOME/path/to/dvc-store`

Here I'm specifically talking about the scenario of using `dvc get`, where, as the docs state, "DVC repos should have a default DVC remote containing the target actual for this command to work". For our use case, a default remote doesn't really work, because the remote location depends on the user. One plausible solution would be to have users symlink their mountpoint to a consistent default URL e.g. `ln -s $HOME/path/to/dvc-store /common/path/to/store`  but we cannot do this for security reasons.

What I am proposing more broadly is to allow DVC to auto-discover FileSystem plugins beyond the existing list here: https://github.com/iterative/dvc-objects/blob/main/src/dvc_objects/fs/scheme.py. 
MLFlow has a good mechanism for doing something similar using entrypoints here:
https://github.com/mlflow/mlflow/blob/ff689bf5fe3f3f7ec0ccfb5494524a92d5612403/mlflow/store/artifact/artifact_repository_registry.py#L41

This would then allow me to specify my url in the config as something like:
```
['remote "storage"']
    url = drives://path/to/remote/store
```
where `drives` is the discovered name for my own custom plugin which would sub-class `dvc_objects.fs.base.FileSystem` in a similar way to the existing file system plugins such as `s3` or `azure`. This plugin would then be distributed through my organisation's internal PyPi server.

Why do I think this is useful? This would allow organisations such as ours to develop our own custom (and in some cases proprietary) storage integrations whilst still leveraging all the existing capabilities of DVC.

I hope this makes sense!
