### ISSUE TITLE
`path.normpath` strips valid local filename characters from paths

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc-objects#177]
https://github.com/iterative/dvc-objects/blob/a1f8c64f584b78eb1c392b1d129b27ca76811b0a/src/dvc_objects/fs/path.py#L47-L49

from https://stackoverflow.com/questions/74934228/what-are-the-file-name-rules-in-dvc-and-can-they-be-controlled-via-config

If a local filename contains a newline (which is valid on posix filesystems), `urlsplit` will silently remove the newline from the path. `urlsplit` enforces that URLs conform with [RFC2396](https://datatracker.ietf.org/doc/html/rfc2396.html). DVC doesn't really differentiate between paths and URLs (so it makes sense for the default `Path` implementation to handle URLs), but local filesystem paths are not actually URLs.

The example case uses newlines, but there are other characters that are not valid in URLs that are still valid on local filesystems (especially on posix which pretty much allows anything in filenames). We probably need an overridden `LocalFilesystemPath.normpath` implementation that does not use `urlsplit`/`urlunsplit`.

**Comment by jorgeorpinel** [comment]
Assuming YAML also supports any character, can we check that the file exists instead of trying to validate the string? Then assume its a URL if not (and validate that).

> What should happen if there's a file name that's also a valid URL though?

**Comment by pmrowla** [comment]
There's no guarantee that the file exists (for example we could be checking the path name for a stage output that has not been generated yet). We already know whether or not we are looking at a local path vs URL (based on whether or not we have the `http://`/`s3://`/etc scheme). We just need to handle this case properly in `LocalFilesystem.path`
