### ISSUE TITLE
[Bug] Lowerbound fsspec due to downstream bug

### ISSUE THREAD

**Issue by houssam7737** [iterative/dvc-objects#205]
Getting the following error from dvc-objects

`File "/somebody/.venv/lib/python3.8/site-packages/dvc_objects/fs/local.py", line 21, in __init__
 from ._local import LocalFileSystem as _LocalFileSystem
File "/somebody/.venv/lib/python3.8/site-packages/dvc_objects/fs/_local.py", line 18, in <module>
from fsspec.utils import isfilelike, stringify_path
ImportError: cannot import name 'isfilelike' from 'fsspec.utils' (/somebody/.venv/lib/python3.8/site-packages/fsspec/utils.py)`

Based on this [stackoverflow](https://stackoverflow.com/questions/72658817/struggling-to-read-csv-files-from-google-cloud-storage-bucket), fsspec needs to be 2022.5.0 or later. Given that the dependency comes from this pkg, the requirement constraint should be specified here.

Thank you!

**Comment by skshetry** [comment]
We require `fsspec>=2022.10.0`.  Can you please share `dvc doctor` output please?

https://github.com/iterative/dvc-objects/blob/04b12d050ea34c82e6b8ca4842cfa0c1f93b296e/setup.cfg#L30

**Comment by houssam7737** [comment]
Oops. Resolved by just using latest version. Sorry for the spam!
