### ISSUE TITLE
cannot import name 'umask' from 'dvc_objects.fs.system'

### ISSUE THREAD

**Issue by marinbouthemy** [iterative/dvc-objects#241]
Hello,

It seems like the latest version of dvc-objects is not working fine for an import. My Github pipeline just broke because of this import:

`ERROR: unexpected error - cannot import name 'umask' from 'dvc_objects.fs.system' (/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/dvc_objects/fs/system.py)
`

I was using this version of DVC:  

`pip install dvc==3.33.0 dvc-azure==2.23.0`

I force an older version of dvc-object to fix this issue.

Thanks a lot

**Comment by charlesmelby** [comment]
Same here

**Comment by efiop** [comment]
@charlesmelby @marinbouthemy @nbgit10 Hey folks, thanks for the report! dvc-data 2.22.4 is out with the fix and should be picked up by older dvc versions, but dvc 3.33.1 is also out with all fixes.
