### ISSUE TITLE
remove dependency on `tqdm`

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-objects#27]

**Comment by casperdcl** [comment]
any reason(s)/feature request(s)?

**Comment by skshetry** [comment]
It’s the responsibility of the application (i.e `dvc`), the progress should be replaced with better callbacks here.

**Comment by skshetry** [comment]
We have removed direct dependency on `tqdm` but `TqdmCallback` still remains in `dvc-objects`.

Which will be removed in upcoming releases. `Callback.as_tqdm_callback` will be removed soon as well. (I want Callback be close to  fsspec's `Callback` interface).

**Comment by skshetry** [comment]
Done in #279.
