### ISSUE TITLE
Enable read-only caches by not writing to cache on check for link types.

### ISSUE THREAD

**Issue by kpoeppel** [iterative/dvc-objects#82]
# Short description
DVC caches could be read-only if the link type check in dvc-objects would not create a new file in the cache and try to link it. Read-only dvc caches are very useful if one uses symlinks anyway in a setting, where many readers read from a joint DVC cache, but do not write there. Some file systems do not allow a distributed multi-write setting and might break because of this single write from multiple dvc pulls.
Of course this should only for symlink caches, not relink based caches.

# Idea for a PR
Search the filesystem for any kind of file and try to link that one instead of creating a new one. If no one exists, use the current setting.

I am also willing to contribute this PR.

**Comment by efiop** [comment]
@kpoeppel Is some particular command raising this error for you? Could you post a verbose log for it, please? Just trying to make sure we have a full picture here.
